var l;l||=typeof Module != 'undefined' ? Module : {};var aa="./this.program",ba=globalThis.document?.currentScript?.src,da="",ea;try{da=(new URL(".",ba)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var q=console.error.bind(console),r,t=!1,fa,u,v,A,C,D,E,ha,ia,ja,ka;
function la(){var a=F.buffer;u=new Int8Array(a);A=new Int16Array(a);v=new Uint8Array(a);C=new Uint16Array(a);D=new Int32Array(a);E=new Uint32Array(a);ha=new Float32Array(a);ia=new Float64Array(a);ja=new BigInt64Array(a);ka=new BigUint64Array(a)}function ma(a){l.onAbort?.(a);a="Aborted("+a+")";q(a);t=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var na;
async function oa(a){if(!r)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==na&&r)a=new Uint8Array(r);else throw"both async and sync fetching of the wasm failed";return a}async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),ma(d)}}
async function qa(a){var b=na;if(!r)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return pa(b,a)}class ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var sa=a=>{for(;0<a.length;)a.shift()(l)},ua=[],va=[],wa=()=>{var a=l.preRun.shift();va.push(a)},G=0,H=null,I=!0,J=[],xa=0,K=0;
class ya{constructor(a){this.xa=a;this.ra=a-24}}var Aa=a=>{var b=K;if(!b)return L(0),0;var c=new ya(b);E[c.ra+16>>2]=b;var d=E[c.ra+4>>2];if(!d)return L(0),b;for(var e of a){if(0===e||e===d)break;if(za(e,d,c.ra+16))return L(e),b}L(d);return b},M=a=>{for(var b="";;){var c=v[a++];if(!c)return b;b+=String.fromCharCode(c)}},O={},P={},Ba={},Q=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ca=a=>{throw new Q(a);};
function Da(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(P.hasOwnProperty(a)){if(c.za)return;throw new Q(`Cannot register type '${d}' twice`);}P[a]=b;delete Ba[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(e=>e()))}function R(a,b,c={}){return Da(a,b,c)}
var Ea=(a,b,c)=>{switch(b){case 1:return c?d=>u[d]:d=>v[d];case 2:return c?d=>A[d>>1]:d=>C[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];case 8:return c?d=>ja[d>>3]:d=>ka[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Fa=[],S=[0,1,,1,null,1,!0,1,!1,1],Ga=a=>{9<a&&0===--S[a+1]&&(S[a]=void 0,Fa.push(a))},Ha=a=>{if(!a)throw new Q(`Cannot use deleted val. handle = ${a}`);return S[a]},Ia=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=
Fa.pop()||S.length;S[b]=a;S[b+1]=1;return b}};function Ja(a){return this.qa(E[a>>2])}var Ka={name:"emscripten::val",qa:a=>{var b=Ha(a);Ga(a);return b},ua:(a,b)=>Ia(b),va:Ja,ta:null},La=(a,b)=>{switch(b){case 4:return function(c){return this.qa(ha[c>>2])};case 8:return function(c){return this.qa(ia[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ma=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Na(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ta)return!0;return!1}
var Oa=(a,b)=>{var c=l;if(void 0===c[a].sa){var d=c[a];c[a]=function(...e){if(!c[a].sa.hasOwnProperty(e.length))throw new Q(`Function '${b}' called with an invalid number of arguments (${e.length}) - expects one of (${c[a].sa})!`);return c[a].sa[e.length].apply(this,e)};c[a].sa=[];c[a].sa[d.wa]=d}},Pa=(a,b,c)=>{if(l.hasOwnProperty(a)){if(void 0===c||void 0!==l[a].sa&&void 0!==l[a].sa[c])throw new Q(`Cannot register public name '${a}' twice`);Oa(a,a);if(l[a].sa.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
l[a].sa[c]=b}else l[a]=b,l[a].wa=c},Qa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c},Ra=class extends Error{constructor(a){super(a);this.name="InternalError"}},Sa=[],T=a=>{var b=Sa[a];b||(Sa[a]=b=Ta.get(a));return b},Ua=(a,b)=>{a=M(a);var c=T(b);if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c};class Va extends Error{}
var Xa=a=>{a=Wa(a);var b=M(a);U(a);return b},Ya=(a,b)=>{function c(f){e[f]||P[f]||(Ba[f]?Ba[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Va(`${a}: `+d.map(Xa).join([", "]));},Za=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new Ra("Mismatched type converter count");for(var k=0;k<d.length;++k)R(d[k],h[k])}var d=[];d.forEach(h=>Ba[h]=a);var e=Array(a.length),f=[],g=0;for(let [h,k]of a.entries())P.hasOwnProperty(k)?e[h]=P[k]:(f.push(k),O.hasOwnProperty(k)||(O[k]=
[]),O[k].push(()=>{e[h]=P[k];++g;g===f.length&&c(e)}));0===f.length&&c(e)},$a=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},V=(a,b,c)=>{var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=
128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},bb=globalThis.TextDecoder&&new TextDecoder,cb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},db=(a=0,b,c)=>{var d=v;b=cb(d,a,b,c);if(16<b-a&&d.buffer&&bb)return bb.decode(d.subarray(a,b));for(c="";a<b;){var e=d[a++];if(e&128){var f=d[a++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=
d[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|d[a++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},gb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,hb=(a,b,c)=>{a>>=1;b=cb(C,a,b/2,c);if(16<b-a&&gb)return gb.decode(C.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(C[a]);return c},ib=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=
0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d},jb=a=>2*a.length,kb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=E[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},lb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},mb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},nb=0,ob=[],pb=a=>{var b=ob.length;ob.push(a);
return b},qb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=E[b+4*d>>2],g=P[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${Xa(f)}`,new Q(a);c[e]=g}return c},rb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(E[b>>2]=Ia(d));return a},sb={},tb=a=>{var b=sb[a];return void 0===b?M(a):b},W={},ub=a=>{if(!(a instanceof ra||"unwind"==a))throw a;},vb=a=>{fa=a;I||0<nb||(l.onExit?.(a),t=!0);throw new ra(a);},wb=a=>{if(!t)try{if(a(),!(I||0<nb))try{fa=a=fa,vb(a)}catch(b){ub(b)}}catch(b){ub(b)}},xb=
{},zb=()=>{if(!yb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in xb)void 0===xb[b]?delete a[b]:a[b]=xb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);yb=c}return yb},yb,Bb=(a,b,c,d)=>{var e={string:m=>{var p=0;if(null!==m&&void 0!==m&&0!==m){p=ab(m)+1;var y=Ab(p);V(m,y,p);p=y}return p},array:m=>{var p=Ab(m.length);u.set(m,p);return p}};a=l["_"+a];
var f=[],g=0;if(d)for(var h=0;h<d.length;h++){var k=e[c[h]];k?(0===g&&(g=X()),f[h]=k(d[h])):f[h]=d[h]}c=a(...f);return c=function(m){0!==g&&Y(g);return"string"===b?m?db(m):"":"boolean"===b?!!m:m}(c)};l.noExitRuntime&&(I=l.noExitRuntime);l.printErr&&(q=l.printErr);l.wasmBinary&&(r=l.wasmBinary);l.thisProgram&&(aa=l.thisProgram);if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.shift()();l.ccall=Bb;
l.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?l["_"+a]:(...f)=>Bb(a,b,c,f,d)};
var Cb,Wa,Db,U,Z,L,Y,Ab,X,Eb,Fb,za,Gb,F,Ta,bc={m:a=>{var b=new ya(a);0==u[b.ra+12]&&(u[b.ra+12]=1,xa--);u[b.ra+13]=0;J.push(b);Fb(a);return Gb(a)},s:()=>{Z(0,0);var a=J.pop();Eb(a.xa);K=0},a:()=>Aa([]),h:a=>Aa([a]),T:()=>{var a=J.pop();a||ma("no exception to throw");var b=a.xa;0==u[a.ra+13]&&(J.push(a),u[a.ra+13]=1,u[a.ra+12]=0,xa++);K=b;throw K;},r:(a,b,c)=>{var d=new ya(a);E[d.ra+16>>2]=0;E[d.ra+4>>2]=b;E[d.ra+8>>2]=c;K=a;xa++;throw K;},S:()=>xa,f:a=>{K||=a;throw K;},P:()=>ma(""),E:(a,b,c,d,e)=>
{b=M(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}R(a,{name:b,qa:f,ua:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},va:Ea(b,c,!d),ta:null})},$:(a,b,c,d)=>{b=M(b);R(a,{name:b,qa:function(e){return!!e},ua:function(e,f){return f?c:d},va:function(e){return this.qa(v[e])},ta:null})},Z:a=>R(a,Ka),D:(a,b,c)=>{b=M(b);R(a,{name:b,qa:d=>d,ua:(d,e)=>e,va:La(b,c),ta:null})},t:(a,b,c,d,e,f,g)=>{var h=Qa(b,c);a=M(a);a=$a(a);e=Ua(d,e);Pa(a,function(){Ya(`Cannot call ${a} due to unbound types`,
h)},b-1);Za(h,k=>{var m=a;var p=a;k=[k[0],null].concat(k.slice(1));var y=e,n=k.length;if(2>n)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var z=null!==k[1]&&!1,N=Na(k),ca=!k[0].ya,w=k[0],x=k[1];y=[p,Ca,y,f,Ma,w.qa.bind(w),x?.ua.bind(x)];for(w=2;w<n;++w)x=k[w],y.push(x.ua.bind(x));if(!N)for(w=z?1:2;w<k.length;++w)null!==k[w].ta&&y.push(k[w].ta);N=Na(k);w=k.length-2;var B=[];x=["fn"];z&&x.push("thisWired");for(n=0;n<w;++n)B.push(`arg${n}`),x.push(`arg${n}Wired`);
B=B.join(",");x=x.join(",");B=`return function (${B}) {\n`;N&&(B+="var destructors = [];\n");var eb=N?"destructors":"null",ta="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");z&&(B+=`var thisWired = toClassParamWire(${eb}, this);\n`);for(n=0;n<w;++n){var fb=`toArg${n}Wire`;B+=`var arg${n}Wired = ${fb}(${eb}, arg${n});\n`;ta.push(fb)}B+=(ca||g?"var rv = ":"")+`invoker(${x});\n`;if(N)B+="runDestructors(destructors);\n";else for(n=z?1:2;n<k.length;++n)z=
1===n?"thisWired":"arg"+(n-2)+"Wired",null!==k[n].ta&&(B+=`${z}_dtor(${z});\n`,ta.push(`${z}_dtor`));ca&&(B+="var ret = fromRetWire(rv);\nreturn ret;\n");k=(new Function(ta,B+"}\n"))(...y);p=Object.defineProperty(k,"name",{value:p});k=b-1;if(!l.hasOwnProperty(m))throw new Ra("Replacing nonexistent public symbol");void 0!==l[m].sa&&void 0!==k?l[m].sa[k]=p:(l[m]=p,l[m].wa=k);return[]})},q:(a,b,c,d,e)=>{b=M(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}R(a,{name:b,qa:f,ua:(h,k)=>k,va:Ea(b,
c,0!==d),ta:null})},l:(a,b,c)=>{function d(f){return new e(u.buffer,E[f+4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=M(c);R(a,{name:c,qa:d,va:d},{za:!0})},_:(a,b)=>{b=M(b);R(a,{name:b,qa(c){var d=(d=c+4)?db(d,E[c>>2],!0):"";U(c);return d},ua(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new Q("Cannot pass non-string to std::string");
var f=e?ab(d):d.length;var g=Cb(4+f+1),h=g+4;E[g>>2]=f;e?V(d,h,f+1):v.set(d,h);null!==c&&c.push(U,g);return g},va:Ja,ta(c){U(c)}})},y:(a,b,c)=>{c=M(c);if(2===b){var d=hb;var e=ib;var f=jb}else d=kb,e=lb,f=mb;R(a,{name:c,qa:g=>{var h=d(g+4,E[g>>2]*b,!0);U(g);return h},ua:(g,h)=>{if("string"!=typeof h)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),m=Cb(4+k+b);E[m>>2]=k/b;e(h,m+4,k+b);null!==g&&g.push(U,m);return m},va:Ja,ta(g){U(g)}})},F:(a,b)=>{b=M(b);R(a,{ya:!0,name:b,qa:()=>
{},ua:()=>{}})},N:()=>{I=!1;nb=0},C:(a,b,c)=>{var [d,...e]=qb(a,b);b=d.ua.bind(d);var f=e.map(k=>k.va.bind(k));a--;var g={toValue:Ha};a=f.map((k,m)=>{var p=`argFromPtr${m}`;g[p]=k;return`${p}(args${m?"+"+8*m:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=tb,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.ya||(g.toReturnWire=b,g.emval_returnValue=rb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);
h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(k=>k.name)}) => ${d.name}>`;return pb(Object.defineProperty(c,"name",{value:h}))},W:Ga,H:a=>{9<a&&(S[a+1]+=1)},z:(a,b,c,d,e)=>ob[a](b,c,d,e),G:a=>{var b=Ha(a);Ma(b);Ga(a)},V:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);D[b>>2]=a.getUTCSeconds();D[b+4>>2]=a.getUTCMinutes();D[b+8>>2]=a.getUTCHours();
D[b+12>>2]=a.getUTCDate();D[b+16>>2]=a.getUTCMonth();D[b+20>>2]=a.getUTCFullYear()-1900;D[b+24>>2]=a.getUTCDay();D[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},O:(a,b)=>{W[a]&&(clearTimeout(W[a].id),delete W[a]);if(!b)return 0;var c=setTimeout(()=>{delete W[a];wb(()=>Db(a,performance.now()))},b);W[a]={id:c,Aa:b};return 0},X:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();E[a>>2]=60*Math.max(f,e);
D[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(V(a,c,17),V(b,d,17)):(V(a,d,17),V(b,c,17))},Y:()=>Date.now(),U:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-F.buffer.byteLength+65535)/65536|0;try{F.grow(d);la();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
Q:(a,b)=>{var c=0,d=0,e;for(e of zb()){var f=b+c;E[a+d>>2]=f;c+=V(e,f,Infinity)+1;d+=4}return 0},R:(a,b)=>{var c=zb();E[a>>2]=c.length;a=0;for(var d of c)a+=ab(d)+1;E[b>>2]=a;return 0},x:Hb,I:Ib,B:Jb,c:Kb,o:Lb,d:Mb,b:Nb,K:Ob,L:Pb,p:Qb,A:Rb,w:Sb,J:Tb,g:Ub,j:Vb,e:Wb,k:Xb,i:Yb,n:Zb,u:$b,v:ac,M:vb};function Kb(a,b){var c=X();try{return T(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function Wb(a,b,c){var d=X();try{T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}
function Ub(a){var b=X();try{T(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}function Xb(a,b,c,d){var e=X();try{T(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function Yb(a,b,c,d,e){var f=X();try{T(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}function Nb(a,b,c,d){var e=X();try{return T(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function Mb(a,b,c){var d=X();try{return T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}
function Hb(a,b){var c=X();try{return T(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function Jb(a,b,c,d,e,f){var g=X();try{return T(a)(b,c,d,e,f)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}function Vb(a,b){var c=X();try{T(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function Lb(a,b,c){var d=X();try{return T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function Qb(a,b,c,d,e,f,g){var h=X();try{return T(a)(b,c,d,e,f,g)}catch(k){Y(h);if(k!==k+0)throw k;Z(1,0)}}
function Pb(a,b,c,d,e,f){var g=X();try{return T(a)(b,c,d,e,f)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}function Ob(a,b,c,d,e,f){var g=X();try{return T(a)(b,c,d,e,f)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}function Tb(a,b,c){var d=X();try{return T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function Rb(a,b,c,d,e,f,g,h){var k=X();try{return T(a)(b,c,d,e,f,g,h)}catch(m){Y(k);if(m!==m+0)throw m;Z(1,0)}}
function Zb(a,b,c,d,e,f,g,h){var k=X();try{T(a)(b,c,d,e,f,g,h)}catch(m){Y(k);if(m!==m+0)throw m;Z(1,0)}}function Sb(a,b,c,d,e,f,g,h,k,m,p,y){var n=X();try{return T(a)(b,c,d,e,f,g,h,k,m,p,y)}catch(z){Y(n);if(z!==z+0)throw z;Z(1,0)}}function $b(a,b,c,d,e,f,g,h,k,m,p){var y=X();try{T(a)(b,c,d,e,f,g,h,k,m,p)}catch(n){Y(y);if(n!==n+0)throw n;Z(1,0)}}function ac(a,b,c,d,e,f,g,h,k,m,p,y,n,z,N,ca){var w=X();try{T(a)(b,c,d,e,f,g,h,k,m,p,y,n,z,N,ca)}catch(x){Y(w);if(x!==x+0)throw x;Z(1,0)}}
function Ib(a,b,c){var d=X();try{return T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}
function cc(){function a(){l.calledRun=!0;if(!t){dc.ba();l.onRuntimeInitialized?.();if(l.postRun)for("function"==typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var b=l.postRun.shift();ua.push(b)}sa(ua)}}if(0<G)H=cc;else{if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)wa();sa(va);0<G?H=cc:l.setStatus?(l.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>l.setStatus(""),1);a()},1)):a()}}var dc;
(async function(){function a(c){c=dc=c.exports;Cb=c.ca;Wa=c.da;Db=c.fa;U=c.ga;Z=c.ha;L=c.ia;Y=c.ja;Ab=c.ka;X=c.la;Eb=c.ma;Fb=c.na;za=c.oa;Gb=c.pa;F=c.aa;Ta=c.ea;la();G--;l.monitorRunDependencies?.(G);0==G&&H&&(c=H,H=null,c());return dc}G++;l.monitorRunDependencies?.(G);var b={a:bc};if(l.instantiateWasm)return new Promise(c=>{l.instantiateWasm(b,(d,e)=>{c(a(d,e))})});na??=l.locateFile?l.locateFile("csv_converter.wasm",da):da+"csv_converter.wasm";return a((await qa(b)).instance)})();cc();
